---
configs:
  use: 'production'
  production: 
    loris_version: 16.0.2
    loris_url: 'http://localhost:6464'
    hostname: 'loris'
    vm_name: 'Loris VM'
    ip_address: '192.168.33.11'
    memory: 2048
    cpus: 2
    http_port: 6464
    ssh_port: 4646
    data_folder: '/path/to/data/'
    mysql_root_password: changeme 
    mysql_lorisuser_password: changeme 
    lorisadmin_password: changeme
    web_admin_password: changeme
  development:
    loris_version: 16.1.0
    loris_url: 'http://localhost:6565'
    hostname: 'lorisdev'
    vm_name: 'Loris developement'
    ip_address: '192.168.33.21'
    memory: 1024
    cpus: 1
    http_port: 6565
    ssh_port: 5656
    data_folder: '/path/to/data'
    mysql_root_password: changeme
    mysql_lorisuser_password: changeme
    loris_admin_password: changeme
    web_admin_password: changeme

